sonar.projectKey=botnethunter
sonar.projectName=BotNetHunter
sonar.projectVersion=1.0.0

sonar.sources=analyzers,api,app,config,core,models,static,templates,utils
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/venv/**,data/**,dist/**

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
